Controls = {}

Controls.Groups = {
  [0] = "INPUTGROUP_MOVE",
  [1] = "INPUTGROUP_LOOK",
  [2] = "INPUTGROUP_WHEEL",
  [3] = "INPUTGROUP_CELLPHONE_NAVIGATE",
  [4] = "INPUTGROUP_CELLPHONE_NAVIGATE_UD",
  [5] = "INPUTGROUP_CELLPHONE_NAVIGATE_LR",
  [6] = "INPUTGROUP_FRONTEND_DPAD_ALL",
  [7] = "INPUTGROUP_FRONTEND_DPAD_UD",
  [8] = "INPUTGROUP_FRONTEND_DPAD_LR",
  [9] = "INPUTGROUP_FRONTEND_LSTICK_ALL",
  [10] = "INPUTGROUP_FRONTEND_RSTICK_ALL",
  [11] = "INPUTGROUP_FRONTEND_GENERIC_UD",
  [12] = "INPUTGROUP_FRONTEND_GENERIC_LR",
  [13] = "INPUTGROUP_FRONTEND_GENERIC_ALL",
  [14] = "INPUTGROUP_FRONTEND_BUMPERS",
  [15] = "INPUTGROUP_FRONTEND_TRIGGERS",
  [16] = "INPUTGROUP_FRONTEND_STICKS",
  [17] = "INPUTGROUP_SCRIPT_DPAD_ALL",
  [18] = "INPUTGROUP_SCRIPT_DPAD_UD",
  [19] = "INPUTGROUP_SCRIPT_DPAD_LR",
  [20] = "INPUTGROUP_SCRIPT_LSTICK_ALL",
  [21] = "INPUTGROUP_SCRIPT_RSTICK_ALL",
  [22] = "INPUTGROUP_SCRIPT_BUMPERS",
  [23] = "INPUTGROUP_SCRIPT_TRIGGERS",
  [24] = "INPUTGROUP_WEAPON_WHEEL_CYCLE",
  [25] = "INPUTGROUP_FLY",
  [26] = "INPUTGROUP_SUB",
  [27] = "INPUTGROUP_VEH_MOVE_ALL",
  [28] = "INPUTGROUP_CURSOR",
  [29] = "INPUTGROUP_CURSOR_SCROLL",
  [30] = "INPUTGROUP_SNIPER_ZOOM_SECONDARY",
  [31] = "INPUTGROUP_VEH_HYDRAULICS_CONTROL"
}

Controls.GroupsLookup = {}
for k,v in pairs(Controls.Groups) do
  Controls.GroupsLookup[v]          = k
  Controls.GroupsLookup[v:lower()]  = k
end

Controls.Inputs = {  
  [0] = {name = "INPUT_NEXT_CAMERA", qwerty = "V", xbox = "BACK"},
  [1] = {name = "INPUT_LOOK_LR", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [2] = {name = "INPUT_LOOK_UD", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [3] = {name = "INPUT_LOOK_UP_ONLY", qwerty = "(NONE)", xbox = "RIGHT STICK"},
  [4] = {name = "INPUT_LOOK_DOWN_ONLY", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [5] = {name = "INPUT_LOOK_LEFT_ONLY", qwerty = "(NONE)", xbox = "RIGHT STICK"},
  [6] = {name = "INPUT_LOOK_RIGHT_ONLY", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [7] = {name = "INPUT_CINEMATIC_SLOWMO", qwerty = "(NONE)", xbox = "R3"},
  [8] = {name = "INPUT_SCRIPTED_FLY_UD", qwerty = "S", xbox = "LEFT STICK"},
  [9] = {name = "INPUT_SCRIPTED_FLY_LR", qwerty = "D", xbox = "LEFT STICK"},
  [10] = {name = "INPUT_SCRIPTED_FLY_ZUP", qwerty = "PAGEUP", xbox = "LT"},
  [11] = {name = "INPUT_SCRIPTED_FLY_ZDOWN", qwerty = "PAGEDOWN", xbox = "RT"},
  [12] = {name = "INPUT_WEAPON_WHEEL_UD", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [13] = {name = "INPUT_WEAPON_WHEEL_LR", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [14] = {name = "INPUT_WEAPON_WHEEL_NEXT", qwerty = "SCROLLWHEEL DOWN", xbox = "DPAD RIGHT"},
  [15] = {name = "INPUT_WEAPON_WHEEL_PREV", qwerty = "SCROLLWHEEL UP", xbox = "DPAD LEFT"},
  [16] = {name = "INPUT_SELECT_NEXT_WEAPON", qwerty = "SCROLLWHEEL DOWN", xbox = "(NONE)"},
  [17] = {name = "INPUT_SELECT_PREV_WEAPON", qwerty = "SCROLLWHEEL UP", xbox = "(NONE)"},
  [18] = {name = "INPUT_SKIP_CUTSCENE", qwerty = "ENTER / LEFT MOUSE BUTTON / SPACEBAR", xbox = "A"},
  [19] = {name = "INPUT_CHARACTER_WHEEL", qwerty = "LEFT ALT", xbox = "DPAD DOWN"},
  [20] = {name = "INPUT_MULTIPLAYER_INFO", qwerty = "Z", xbox = "DPAD DOWN"},
  [21] = {name = "INPUT_SPRINT", qwerty = "LEFT SHIFT", xbox = "A"},
  [22] = {name = "INPUT_JUMP", qwerty = "SPACEBAR", xbox = "X"},
  [23] = {name = "INPUT_ENTER", qwerty = "F", xbox = "Y"},
  [24] = {name = "INPUT_ATTACK", qwerty = "LEFT MOUSE BUTTON", xbox = "RT"},
  [25] = {name = "INPUT_AIM", qwerty = "RIGHT MOUSE BUTTON", xbox = "LT"},
  [26] = {name = "INPUT_LOOK_BEHIND", qwerty = "C", xbox = "R3"},
  [27] = {name = "INPUT_PHONE", qwerty = "ARROW UP / SCROLLWHEEL BUTTON (PRESS)", xbox = "DPAD UP"},
  [28] = {name = "INPUT_SPECIAL_ABILITY", qwerty = "(NONE)", xbox = "L3"},
  [29] = {name = "INPUT_SPECIAL_ABILITY_SECONDARY", qwerty = "B", xbox = "R3"},
  [30] = {name = "INPUT_MOVE_LR", qwerty = "D", xbox = "LEFT STICK"},
  [31] = {name = "INPUT_MOVE_UD", qwerty = "S", xbox = "LEFT STICK"},
  [32] = {name = "INPUT_MOVE_UP_ONLY", qwerty = "W", xbox = "LEFT STICK"},
  [33] = {name = "INPUT_MOVE_DOWN_ONLY", qwerty = "S", xbox = "LEFT STICK"},
  [34] = {name = "INPUT_MOVE_LEFT_ONLY", qwerty = "A", xbox = "LEFT STICK"},
  [35] = {name = "INPUT_MOVE_RIGHT_ONLY", qwerty = "D", xbox = "LEFT STICK"},
  [36] = {name = "INPUT_DUCK", qwerty = "LEFT CTRL", xbox = "L3"},
  [37] = {name = "INPUT_SELECT_WEAPON", qwerty = "TAB", xbox = "LB"},
  [38] = {name = "INPUT_PICKUP", qwerty = "E", xbox = "LB"},
  [39] = {name = "INPUT_SNIPER_ZOOM", qwerty = "[", xbox = "LEFT STICK"},
  [40] = {name = "INPUT_SNIPER_ZOOM_IN_ONLY", qwerty = "]", xbox = "LEFT STICK"},
  [41] = {name = "INPUT_SNIPER_ZOOM_OUT_ONLY", qwerty = "[", xbox = "LEFT STICK"},
  [42] = {name = "INPUT_SNIPER_ZOOM_IN_SECONDARY", qwerty = "]", xbox = "DPAD UP"},
  [43] = {name = "INPUT_SNIPER_ZOOM_OUT_SECONDARY", qwerty = "[", xbox = "DPAD DOWN"},
  [44] = {name = "INPUT_COVER", qwerty = "Q", xbox = "RB"},
  [45] = {name = "INPUT_RELOAD", qwerty = "R", xbox = "B"},
  [46] = {name = "INPUT_TALK", qwerty = "E", xbox = "DPAD RIGHT"},
  [47] = {name = "INPUT_DETONATE", qwerty = "G", xbox = "DPAD LEFT"},
  [48] = {name = "INPUT_HUD_SPECIAL", qwerty = "Z", xbox = "DPAD DOWN"},
  [49] = {name = "INPUT_ARREST", qwerty = "F", xbox = "Y"},
  [50] = {name = "INPUT_ACCURATE_AIM", qwerty = "SCROLLWHEEL DOWN", xbox = "R3"},
  [51] = {name = "INPUT_CONTEXT", qwerty = "E", xbox = "DPAD RIGHT"},
  [52] = {name = "INPUT_CONTEXT_SECONDARY", qwerty = "Q", xbox = "DPAD LEFT"},
  [53] = {name = "INPUT_WEAPON_SPECIAL", qwerty = "(NONE)", xbox = "Y"},
  [54] = {name = "INPUT_WEAPON_SPECIAL_TWO", qwerty = "E", xbox = "DPAD RIGHT"},
  [55] = {name = "INPUT_DIVE", qwerty = "SPACEBAR", xbox = "RB"},
  [56] = {name = "INPUT_DROP_WEAPON", qwerty = "F9", xbox = "Y"},
  [57] = {name = "INPUT_DROP_AMMO", qwerty = "F10", xbox = "B"},
  [58] = {name = "INPUT_THROW_GRENADE", qwerty = "G", xbox = "DPAD LEFT"},
  [59] = {name = "INPUT_VEH_MOVE_LR", qwerty = "D", xbox = "LEFT STICK"},
  [60] = {name = "INPUT_VEH_MOVE_UD", qwerty = "LEFT CTRL", xbox = "LEFT STICK"},
  [61] = {name = "INPUT_VEH_MOVE_UP_ONLY", qwerty = "LEFT SHIFT", xbox = "LEFT STICK"},
  [62] = {name = "INPUT_VEH_MOVE_DOWN_ONLY", qwerty = "LEFT CTRL", xbox = "LEFT STICK"},
  [63] = {name = "INPUT_VEH_MOVE_LEFT_ONLY", qwerty = "A", xbox = "LEFT STICK"},
  [64] = {name = "INPUT_VEH_MOVE_RIGHT_ONLY", qwerty = "D", xbox = "LEFT STICK"},
  [65] = {name = "INPUT_VEH_SPECIAL", qwerty = "(NONE)", xbox = "(NONE)"},
  [66] = {name = "INPUT_VEH_GUN_LR", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [67] = {name = "INPUT_VEH_GUN_UD", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [68] = {name = "INPUT_VEH_AIM", qwerty = "RIGHT MOUSE BUTTON", xbox = "LB"},
  [69] = {name = "INPUT_VEH_ATTACK", qwerty = "LEFT MOUSE BUTTON", xbox = "RB"},
  [70] = {name = "INPUT_VEH_ATTACK2", qwerty = "RIGHT MOUSE BUTTON", xbox = "A"},
  [71] = {name = "INPUT_VEH_ACCELERATE", qwerty = "W", xbox = "RT"},
  [72] = {name = "INPUT_VEH_BRAKE", qwerty = "S", xbox = "LT"},
  [73] = {name = "INPUT_VEH_DUCK", qwerty = "X", xbox = "A"},
  [74] = {name = "INPUT_VEH_HEADLIGHT", qwerty = "H", xbox = "DPAD RIGHT"},
  [75] = {name = "INPUT_VEH_EXIT", qwerty = "F", xbox = "Y"},
  [76] = {name = "INPUT_VEH_HANDBRAKE", qwerty = "SPACEBAR", xbox = "RB"},
  [77] = {name = "INPUT_VEH_HOTWIRE_LEFT", qwerty = "W", xbox = "LT"},
  [78] = {name = "INPUT_VEH_HOTWIRE_RIGHT", qwerty = "S", xbox = "RT"},
  [79] = {name = "INPUT_VEH_LOOK_BEHIND", qwerty = "C", xbox = "R3"},
  [80] = {name = "INPUT_VEH_CIN_CAM", qwerty = "R", xbox = "B"},
  [81] = {name = "INPUT_VEH_NEXT_RADIO", qwerty = ".", xbox = "(NONE)"},
  [82] = {name = "INPUT_VEH_PREV_RADIO", qwerty = ",", xbox = "(NONE)"},
  [83] = {name = "INPUT_VEH_NEXT_RADIO_TRACK", qwerty = "=", xbox = "(NONE)"},
  [84] = {name = "INPUT_VEH_PREV_RADIO_TRACK", qwerty = "-", xbox = "(NONE)"},
  [85] = {name = "INPUT_VEH_RADIO_WHEEL", qwerty = "Q", xbox = "DPAD LEFT"},
  [86] = {name = "INPUT_VEH_HORN", qwerty = "E", xbox = "L3"},
  [87] = {name = "INPUT_VEH_FLY_THROTTLE_UP", qwerty = "W", xbox = "RT"},
  [88] = {name = "INPUT_VEH_FLY_THROTTLE_DOWN", qwerty = "S", xbox = "LT"},
  [89] = {name = "INPUT_VEH_FLY_YAW_LEFT", qwerty = "A", xbox = "LB"},
  [90] = {name = "INPUT_VEH_FLY_YAW_RIGHT", qwerty = "D", xbox = "RB"},
  [91] = {name = "INPUT_VEH_PASSENGER_AIM", qwerty = "RIGHT MOUSE BUTTON", xbox = "LT"},
  [92] = {name = "INPUT_VEH_PASSENGER_ATTACK", qwerty = "LEFT MOUSE BUTTON", xbox = "RT"},
  [93] = {name = "INPUT_VEH_SPECIAL_ABILITY_FRANKLIN", qwerty = "(NONE)", xbox = "R3"},
  [94] = {name = "INPUT_VEH_STUNT_UD", qwerty = "(NONE)", xbox = "(NONE)"},
  [95] = {name = "INPUT_VEH_CINEMATIC_UD", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [96] = {name = "INPUT_VEH_CINEMATIC_UP_ONLY", qwerty = "NUMPAD- / SCROLLWHEEL UP", xbox = "(NONE)"},
  [97] = {name = "INPUT_VEH_CINEMATIC_DOWN_ONLY", qwerty = "NUMPAD+ / SCROLLWHEEL DOWN", xbox = "(NONE)"},
  [98] = {name = "INPUT_VEH_CINEMATIC_LR", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [99] = {name = "INPUT_VEH_SELECT_NEXT_WEAPON", qwerty = "SCROLLWHEEL UP", xbox = "X"},
  [100] = {name = "INPUT_VEH_SELECT_PREV_WEAPON", qwerty = "[", xbox = "(NONE)"},
  [101] = {name = "INPUT_VEH_ROOF", qwerty = "H", xbox = "DPAD RIGHT"},
  [102] = {name = "INPUT_VEH_JUMP", qwerty = "SPACEBAR", xbox = "RB"},
  [103] = {name = "INPUT_VEH_GRAPPLING_HOOK", qwerty = "E", xbox = "DPAD RIGHT"},
  [104] = {name = "INPUT_VEH_SHUFFLE", qwerty = "H", xbox = "DPAD RIGHT"},
  [105] = {name = "INPUT_VEH_DROP_PROJECTILE", qwerty = "X", xbox = "A"},
  [106] = {name = "INPUT_VEH_MOUSE_CONTROL_OVERRIDE", qwerty = "LEFT MOUSE BUTTON", xbox = "(NONE)"},
  [107] = {name = "INPUT_VEH_FLY_ROLL_LR", qwerty = "NUMPAD 6", xbox = "LEFT STICK"},
  [108] = {name = "INPUT_VEH_FLY_ROLL_LEFT_ONLY", qwerty = "NUMPAD 4", xbox = "LEFT STICK"},
  [109] = {name = "INPUT_VEH_FLY_ROLL_RIGHT_ONLY", qwerty = "NUMPAD 6", xbox = "LEFT STICK"},
  [110] = {name = "INPUT_VEH_FLY_PITCH_UD", qwerty = "NUMPAD 5", xbox = "LEFT STICK"},
  [111] = {name = "INPUT_VEH_FLY_PITCH_UP_ONLY", qwerty = "NUMPAD 8", xbox = "LEFT STICK"},
  [112] = {name = "INPUT_VEH_FLY_PITCH_DOWN_ONLY", qwerty = "NUMPAD 5", xbox = "LEFT STICK"},
  [113] = {name = "INPUT_VEH_FLY_UNDERCARRIAGE", qwerty = "G", xbox = "L3"},
  [114] = {name = "INPUT_VEH_FLY_ATTACK", qwerty = "RIGHT MOUSE BUTTON", xbox = "A"},
  [115] = {name = "INPUT_VEH_FLY_SELECT_NEXT_WEAPON", qwerty = "SCROLLWHEEL UP", xbox = "DPAD LEFT"},
  [116] = {name = "INPUT_VEH_FLY_SELECT_PREV_WEAPON", qwerty = "[", xbox = "(NONE)"},
  [117] = {name = "INPUT_VEH_FLY_SELECT_TARGET_LEFT", qwerty = "NUMPAD 7", xbox = "LB"},
  [118] = {name = "INPUT_VEH_FLY_SELECT_TARGET_RIGHT", qwerty = "NUMPAD 9", xbox = "RB"},
  [119] = {name = "INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE", qwerty = "E", xbox = "DPAD RIGHT"},
  [120] = {name = "INPUT_VEH_FLY_DUCK", qwerty = "X", xbox = "A"},
  [121] = {name = "INPUT_VEH_FLY_ATTACK_CAMERA", qwerty = "INSERT", xbox = "R3"},
  [122] = {name = "INPUT_VEH_FLY_MOUSE_CONTROL_OVERRIDE", qwerty = "LEFT MOUSE BUTTON", xbox = "(NONE)"},
  [123] = {name = "INPUT_VEH_SUB_TURN_LR", qwerty = "NUMPAD 6", xbox = "LEFT STICK"},
  [124] = {name = "INPUT_VEH_SUB_TURN_LEFT_ONLY", qwerty = "NUMPAD 4", xbox = "LEFT STICK"},
  [125] = {name = "INPUT_VEH_SUB_TURN_RIGHT_ONLY", qwerty = "NUMPAD 6", xbox = "LEFT STICK"},
  [126] = {name = "INPUT_VEH_SUB_PITCH_UD", qwerty = "NUMPAD 5", xbox = "LEFT STICK"},
  [127] = {name = "INPUT_VEH_SUB_PITCH_UP_ONLY", qwerty = "NUMPAD 8", xbox = "LEFT STICK"},
  [128] = {name = "INPUT_VEH_SUB_PITCH_DOWN_ONLY", qwerty = "NUMPAD 5", xbox = "LEFT STICK"},
  [129] = {name = "INPUT_VEH_SUB_THROTTLE_UP", qwerty = "W", xbox = "RT"},
  [130] = {name = "INPUT_VEH_SUB_THROTTLE_DOWN", qwerty = "S", xbox = "LT"},
  [131] = {name = "INPUT_VEH_SUB_ASCEND", qwerty = "LEFT SHIFT", xbox = "X"},
  [132] = {name = "INPUT_VEH_SUB_DESCEND", qwerty = "LEFT CTRL", xbox = "A"},
  [133] = {name = "INPUT_VEH_SUB_TURN_HARD_LEFT", qwerty = "A", xbox = "LB"},
  [134] = {name = "INPUT_VEH_SUB_TURN_HARD_RIGHT", qwerty = "D", xbox = "RB"},
  [135] = {name = "INPUT_VEH_SUB_MOUSE_CONTROL_OVERRIDE", qwerty = "LEFT MOUSE BUTTON", xbox = "(NONE)"},
  [136] = {name = "INPUT_VEH_PUSHBIKE_PEDAL", qwerty = "W", xbox = "A"},
  [137] = {name = "INPUT_VEH_PUSHBIKE_SPRINT", qwerty = "CAPSLOCK", xbox = "A"},
  [138] = {name = "INPUT_VEH_PUSHBIKE_FRONT_BRAKE", qwerty = "Q", xbox = "LT"},
  [139] = {name = "INPUT_VEH_PUSHBIKE_REAR_BRAKE", qwerty = "S", xbox = "RT"},
  [140] = {name = "INPUT_MELEE_ATTACK_LIGHT", qwerty = "R", xbox = "B"},
  [141] = {name = "INPUT_MELEE_ATTACK_HEAVY", qwerty = "Q", xbox = "A"},
  [142] = {name = "INPUT_MELEE_ATTACK_ALTERNATE", qwerty = "LEFT MOUSE BUTTON", xbox = "RT"},
  [143] = {name = "INPUT_MELEE_BLOCK", qwerty = "SPACEBAR", xbox = "X"},
  [144] = {name = "INPUT_PARACHUTE_DEPLOY", qwerty = "F / LEFT MOUSE BUTTON", xbox = "Y"},
  [145] = {name = "INPUT_PARACHUTE_DETACH", qwerty = "F", xbox = "Y"},
  [146] = {name = "INPUT_PARACHUTE_TURN_LR", qwerty = "D", xbox = "LEFT STICK"},
  [147] = {name = "INPUT_PARACHUTE_TURN_LEFT_ONLY", qwerty = "A", xbox = "LEFT STICK"},
  [148] = {name = "INPUT_PARACHUTE_TURN_RIGHT_ONLY", qwerty = "D", xbox = "LEFT STICK"},
  [149] = {name = "INPUT_PARACHUTE_PITCH_UD", qwerty = "S", xbox = "LEFT STICK"},
  [150] = {name = "INPUT_PARACHUTE_PITCH_UP_ONLY", qwerty = "W", xbox = "LEFT STICK"},
  [151] = {name = "INPUT_PARACHUTE_PITCH_DOWN_ONLY", qwerty = "S", xbox = "LEFT STICK"},
  [152] = {name = "INPUT_PARACHUTE_BRAKE_LEFT", qwerty = "Q", xbox = "LB"},
  [153] = {name = "INPUT_PARACHUTE_BRAKE_RIGHT", qwerty = "E", xbox = "RB"},
  [154] = {name = "INPUT_PARACHUTE_SMOKE", qwerty = "X", xbox = "A"},
  [155] = {name = "INPUT_PARACHUTE_PRECISION_LANDING", qwerty = "LEFT SHIFT", xbox = "(NONE)"},
  [156] = {name = "INPUT_MAP", qwerty = "(NONE)", xbox = "(NONE)"},
  [157] = {name = "INPUT_SELECT_WEAPON_UNARMED", qwerty = "1", xbox = "(NONE)"},
  [158] = {name = "INPUT_SELECT_WEAPON_MELEE", qwerty = "2", xbox = "(NONE)"},
  [159] = {name = "INPUT_SELECT_WEAPON_HANDGUN", qwerty = "6", xbox = "(NONE)"},
  [160] = {name = "INPUT_SELECT_WEAPON_SHOTGUN", qwerty = "3", xbox = "(NONE)"},
  [161] = {name = "INPUT_SELECT_WEAPON_SMG", qwerty = "7", xbox = "(NONE)"},
  [162] = {name = "INPUT_SELECT_WEAPON_AUTO_RIFLE", qwerty = "8", xbox = "(NONE)"},
  [163] = {name = "INPUT_SELECT_WEAPON_SNIPER", qwerty = "9", xbox = "(NONE)"},
  [164] = {name = "INPUT_SELECT_WEAPON_HEAVY", qwerty = "4", xbox = "(NONE)"},
  [165] = {name = "INPUT_SELECT_WEAPON_SPECIAL", qwerty = "5", xbox = "(NONE)"},
  [166] = {name = "INPUT_SELECT_CHARACTER_MICHAEL", qwerty = "F5", xbox = "(NONE)"},
  [167] = {name = "INPUT_SELECT_CHARACTER_FRANKLIN", qwerty = "F6", xbox = "(NONE)"},
  [168] = {name = "INPUT_SELECT_CHARACTER_TREVOR", qwerty = "F7", xbox = "(NONE)"},
  [169] = {name = "INPUT_SELECT_CHARACTER_MULTIPLAYER", qwerty = "F8 (CONSOLE)", xbox = "(NONE)"},
  [170] = {name = "INPUT_SAVE_REPLAY_CLIP", qwerty = "F3", xbox = "B"},
  [171] = {name = "INPUT_SPECIAL_ABILITY_PC", qwerty = "CAPSLOCK", xbox = "(NONE)"},
  [172] = {name = "INPUT_CELLPHONE_UP", qwerty = "ARROW UP", xbox = "DPAD UP"},
  [173] = {name = "INPUT_CELLPHONE_DOWN", qwerty = "ARROW DOWN", xbox = "DPAD DOWN"},
  [174] = {name = "INPUT_CELLPHONE_LEFT", qwerty = "ARROW LEFT", xbox = "DPAD LEFT"},
  [175] = {name = "INPUT_CELLPHONE_RIGHT", qwerty = "ARROW RIGHT", xbox = "DPAD RIGHT"},
  [176] = {name = "INPUT_CELLPHONE_SELECT", qwerty = "ENTER / LEFT MOUSE BUTTON", xbox = "A"},
  [177] = {name = "INPUT_CELLPHONE_CANCEL", qwerty = "BACKSPACE / ESC / RIGHT MOUSE BUTTON", xbox = "B"},
  [178] = {name = "INPUT_CELLPHONE_OPTION", qwerty = "DELETE", xbox = "Y"},
  [179] = {name = "INPUT_CELLPHONE_EXTRA_OPTION", qwerty = "SPACEBAR", xbox = "X"},
  [180] = {name = "INPUT_CELLPHONE_SCROLL_FORWARD", qwerty = "SCROLLWHEEL DOWN", xbox = "(NONE)"},
  [181] = {name = "INPUT_CELLPHONE_SCROLL_BACKWARD", qwerty = "SCROLLWHEEL UP", xbox = "(NONE)"},
  [182] = {name = "INPUT_CELLPHONE_CAMERA_FOCUS_LOCK", qwerty = "L", xbox = "RT"},
  [183] = {name = "INPUT_CELLPHONE_CAMERA_GRID", qwerty = "G", xbox = "RB"},
  [184] = {name = "INPUT_CELLPHONE_CAMERA_SELFIE", qwerty = "E", xbox = "R3"},
  [185] = {name = "INPUT_CELLPHONE_CAMERA_DOF", qwerty = "F", xbox = "LB"},
  [186] = {name = "INPUT_CELLPHONE_CAMERA_EXPRESSION", qwerty = "X", xbox = "L3"},
  [187] = {name = "INPUT_FRONTEND_DOWN", qwerty = "ARROW DOWN", xbox = "DPAD DOWN"},
  [188] = {name = "INPUT_FRONTEND_UP", qwerty = "ARROW UP", xbox = "DPAD UP"},
  [189] = {name = "INPUT_FRONTEND_LEFT", qwerty = "ARROW LEFT", xbox = "DPAD LEFT"},
  [190] = {name = "INPUT_FRONTEND_RIGHT", qwerty = "ARROW RIGHT", xbox = "DPAD RIGHT"},
  [191] = {name = "INPUT_FRONTEND_RDOWN", qwerty = "ENTER", xbox = "A"},
  [192] = {name = "INPUT_FRONTEND_RUP", qwerty = "TAB", xbox = "Y"},
  [193] = {name = "INPUT_FRONTEND_RLEFT", qwerty = "(NONE)", xbox = "X"},
  [194] = {name = "INPUT_FRONTEND_RRIGHT", qwerty = "BACKSPACE", xbox = "B"},
  [195] = {name = "INPUT_FRONTEND_AXIS_X", qwerty = "D", xbox = "LEFT STICK"},
  [196] = {name = "INPUT_FRONTEND_AXIS_Y", qwerty = "S", xbox = "LEFT STICK"},
  [197] = {name = "INPUT_FRONTEND_RIGHT_AXIS_X", qwerty = "]", xbox = "RIGHT STICK"},
  [198] = {name = "INPUT_FRONTEND_RIGHT_AXIS_Y", qwerty = "SCROLLWHEEL DOWN", xbox = "RIGHT STICK"},
  [199] = {name = "INPUT_FRONTEND_PAUSE", qwerty = "P", xbox = "START"},
  [200] = {name = "INPUT_FRONTEND_PAUSE_ALTERNATE", qwerty = "ESC", xbox = "(NONE)"},
  [201] = {name = "INPUT_FRONTEND_ACCEPT", qwerty = "ENTER / NUMPAD ENTER", xbox = "A"},
  [202] = {name = "INPUT_FRONTEND_CANCEL", qwerty = "BACKSPACE / ESC", xbox = "B"},
  [203] = {name = "INPUT_FRONTEND_X", qwerty = "SPACEBAR", xbox = "X"},
  [204] = {name = "INPUT_FRONTEND_Y", qwerty = "TAB", xbox = "Y"},
  [205] = {name = "INPUT_FRONTEND_LB", qwerty = "Q", xbox = "LB"},
  [206] = {name = "INPUT_FRONTEND_RB", qwerty = "E", xbox = "RB"},
  [207] = {name = "INPUT_FRONTEND_LT", qwerty = "PAGE DOWN", xbox = "LT"},
  [208] = {name = "INPUT_FRONTEND_RT", qwerty = "PAGE UP", xbox = "RT"},
  [209] = {name = "INPUT_FRONTEND_LS", qwerty = "LEFT SHIFT", xbox = "L3"},
  [210] = {name = "INPUT_FRONTEND_RS", qwerty = "LEFT CONTROL", xbox = "R3"},
  [211] = {name = "INPUT_FRONTEND_LEADERBOARD", qwerty = "TAB", xbox = "RB"},
  [212] = {name = "INPUT_FRONTEND_SOCIAL_CLUB", qwerty = "HOME", xbox = "BACK"},
  [213] = {name = "INPUT_FRONTEND_SOCIAL_CLUB_SECONDARY", qwerty = "HOME", xbox = "RB"},
  [214] = {name = "INPUT_FRONTEND_DELETE", qwerty = "DELETE", xbox = "X"},
  [215] = {name = "INPUT_FRONTEND_ENDSCREEN_ACCEPT", qwerty = "ENTER", xbox = "A"},
  [216] = {name = "INPUT_FRONTEND_ENDSCREEN_EXPAND", qwerty = "SPACEBAR", xbox = "X"},
  [217] = {name = "INPUT_FRONTEND_SELECT", qwerty = "CAPSLOCK", xbox = "BACK"},
  [218] = {name = "INPUT_SCRIPT_LEFT_AXIS_X", qwerty = "D", xbox = "LEFT STICK"},
  [219] = {name = "INPUT_SCRIPT_LEFT_AXIS_Y", qwerty = "S", xbox = "LEFT STICK"},
  [220] = {name = "INPUT_SCRIPT_RIGHT_AXIS_X", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [221] = {name = "INPUT_SCRIPT_RIGHT_AXIS_Y", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [222] = {name = "INPUT_SCRIPT_RUP", qwerty = "RIGHT MOUSE BUTTON", xbox = "Y"},
  [223] = {name = "INPUT_SCRIPT_RDOWN", qwerty = "LEFT MOUSE BUTTON", xbox = "A"},
  [224] = {name = "INPUT_SCRIPT_RLEFT", qwerty = "LEFT CTRL", xbox = "X"},
  [225] = {name = "INPUT_SCRIPT_RRIGHT", qwerty = "RIGHT MOUSE BUTTON", xbox = "B"},
  [226] = {name = "INPUT_SCRIPT_LB", qwerty = "(NONE)", xbox = "LB"},
  [227] = {name = "INPUT_SCRIPT_RB", qwerty = "(NONE)", xbox = "RB"},
  [228] = {name = "INPUT_SCRIPT_LT", qwerty = "(NONE)", xbox = "LT"},
  [229] = {name = "INPUT_SCRIPT_RT", qwerty = "LEFT MOUSE BUTTON", xbox = "RT"},
  [230] = {name = "INPUT_SCRIPT_LS", qwerty = "(NONE)", xbox = "L3"},
  [231] = {name = "INPUT_SCRIPT_RS", qwerty = "(NONE)", xbox = "R3"},
  [232] = {name = "INPUT_SCRIPT_PAD_UP", qwerty = "W", xbox = "DPAD UP"},
  [233] = {name = "INPUT_SCRIPT_PAD_DOWN", qwerty = "S", xbox = "DPAD DOWN"},
  [234] = {name = "INPUT_SCRIPT_PAD_LEFT", qwerty = "A", xbox = "DPAD LEFT"},
  [235] = {name = "INPUT_SCRIPT_PAD_RIGHT", qwerty = "D", xbox = "DPAD RIGHT"},
  [236] = {name = "INPUT_SCRIPT_SELECT", qwerty = "V", xbox = "BACK"},
  [237] = {name = "INPUT_CURSOR_ACCEPT", qwerty = "LEFT MOUSE BUTTON", xbox = "(NONE)"},
  [238] = {name = "INPUT_CURSOR_CANCEL", qwerty = "RIGHT MOUSE BUTTON", xbox = "(NONE)"},
  [239] = {name = "INPUT_CURSOR_X", qwerty = "(NONE)", xbox = "(NONE)"},
  [240] = {name = "INPUT_CURSOR_Y", qwerty = "(NONE)", xbox = "(NONE)"},
  [241] = {name = "INPUT_CURSOR_SCROLL_UP", qwerty = "SCROLLWHEEL UP", xbox = "(NONE)"},
  [242] = {name = "INPUT_CURSOR_SCROLL_DOWN", qwerty = "SCROLLWHEEL DOWN", xbox = "(NONE)"},
  [243] = {name = "INPUT_ENTER_CHEAT_CODE", qwerty = "~ / `", xbox = "(NONE)"},
  [244] = {name = "INPUT_INTERACTION_MENU", qwerty = "M", xbox = "BACK"},
  [245] = {name = "INPUT_MP_TEXT_CHAT_ALL", qwerty = "T", xbox = "(NONE)"},
  [246] = {name = "INPUT_MP_TEXT_CHAT_TEAM", qwerty = "Y", xbox = "(NONE)"},
  [247] = {name = "INPUT_MP_TEXT_CHAT_FRIENDS", qwerty = "(NONE)", xbox = "(NONE)"},
  [248] = {name = "INPUT_MP_TEXT_CHAT_CREW", qwerty = "(NONE)", xbox = "(NONE)"},
  [249] = {name = "INPUT_PUSH_TO_TALK", qwerty = "N", xbox = "(NONE)"},
  [250] = {name = "INPUT_CREATOR_LS", qwerty = "R", xbox = "L3"},
  [251] = {name = "INPUT_CREATOR_RS", qwerty = "F", xbox = "R3"},
  [252] = {name = "INPUT_CREATOR_LT", qwerty = "X", xbox = "LT"},
  [253] = {name = "INPUT_CREATOR_RT", qwerty = "C", xbox = "RT"},
  [254] = {name = "INPUT_CREATOR_MENU_TOGGLE", qwerty = "LEFT SHIFT", xbox = "(NONE)"},
  [255] = {name = "INPUT_CREATOR_ACCEPT", qwerty = "SPACEBAR", xbox = "A"},
  [256] = {name = "INPUT_CREATOR_DELETE", qwerty = "DELETE", xbox = "X"},
  [257] = {name = "INPUT_ATTACK2", qwerty = "LEFT MOUSE BUTTON", xbox = "RT"},
  [258] = {name = "INPUT_RAPPEL_JUMP", qwerty = "(NONE)", xbox = "A"},
  [259] = {name = "INPUT_RAPPEL_LONG_JUMP", qwerty = "(NONE)", xbox = "X"},
  [260] = {name = "INPUT_RAPPEL_SMASH_WINDOW", qwerty = "(NONE)", xbox = "RT"},
  [261] = {name = "INPUT_PREV_WEAPON", qwerty = "SCROLLWHEEL UP", xbox = "DPAD LEFT"},
  [262] = {name = "INPUT_NEXT_WEAPON", qwerty = "SCROLLWHEEL DOWN", xbox = "DPAD RIGHT"},
  [263] = {name = "INPUT_MELEE_ATTACK1", qwerty = "R", xbox = "B"},
  [264] = {name = "INPUT_MELEE_ATTACK2", qwerty = "Q", xbox = "A"},
  [265] = {name = "INPUT_WHISTLE", qwerty = "(NONE)", xbox = "(NONE)"},
  [266] = {name = "INPUT_MOVE_LEFT", qwerty = "D", xbox = "LEFT STICK"},
  [267] = {name = "INPUT_MOVE_RIGHT", qwerty = "D", xbox = "LEFT STICK"},
  [268] = {name = "INPUT_MOVE_UP", qwerty = "S", xbox = "LEFT STICK"},
  [269] = {name = "INPUT_MOVE_DOWN", qwerty = "S", xbox = "LEFT STICK"},
  [270] = {name = "INPUT_LOOK_LEFT", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [271] = {name = "INPUT_LOOK_RIGHT", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [272] = {name = "INPUT_LOOK_UP", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [273] = {name = "INPUT_LOOK_DOWN", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [274] = {name = "INPUT_SNIPER_ZOOM_IN", qwerty = "[", xbox = "RIGHT STICK"},
  [275] = {name = "INPUT_SNIPER_ZOOM_OUT", qwerty = "[", xbox = "RIGHT STICK"},
  [276] = {name = "INPUT_SNIPER_ZOOM_IN_ALTERNATE", qwerty = "[", xbox = "LEFT STICK"},
  [277] = {name = "INPUT_SNIPER_ZOOM_OUT_ALTERNATE", qwerty = "[", xbox = "LEFT STICK"},
  [278] = {name = "INPUT_VEH_MOVE_LEFT", qwerty = "D", xbox = "LEFT STICK"},
  [279] = {name = "INPUT_VEH_MOVE_RIGHT", qwerty = "D", xbox = "LEFT STICK"},
  [280] = {name = "INPUT_VEH_MOVE_UP", qwerty = "LEFT CTRL", xbox = "LEFT STICK"},
  [281] = {name = "INPUT_VEH_MOVE_DOWN", qwerty = "LEFT CTRL", xbox = "LEFT STICK"},
  [282] = {name = "INPUT_VEH_GUN_LEFT", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [283] = {name = "INPUT_VEH_GUN_RIGHT", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [284] = {name = "INPUT_VEH_GUN_UP", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [285] = {name = "INPUT_VEH_GUN_DOWN", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [286] = {name = "INPUT_VEH_LOOK_LEFT", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [287] = {name = "INPUT_VEH_LOOK_RIGHT", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [288] = {name = "INPUT_REPLAY_START_STOP_RECORDING", qwerty = "F1", xbox = "A"},
  [289] = {name = "INPUT_REPLAY_START_STOP_RECORDING_SECONDARY", qwerty = "F2", xbox = "X"},
  [290] = {name = "INPUT_SCALED_LOOK_LR", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [291] = {name = "INPUT_SCALED_LOOK_UD", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [292] = {name = "INPUT_SCALED_LOOK_UP_ONLY", qwerty = "(NONE)", xbox = "RIGHT STICK"},
  [293] = {name = "INPUT_SCALED_LOOK_DOWN_ONLY", qwerty = "(NONE)", xbox = "RIGHT STICK"},
  [294] = {name = "INPUT_SCALED_LOOK_LEFT_ONLY", qwerty = "(NONE)", xbox = "RIGHT STICK"},
  [295] = {name = "INPUT_SCALED_LOOK_RIGHT_ONLY", qwerty = "(NONE)", xbox = "RIGHT STICK"},
  [296] = {name = "INPUT_REPLAY_MARKER_DELETE", qwerty = "DELETE", xbox = "X"},
  [297] = {name = "INPUT_REPLAY_CLIP_DELETE", qwerty = "DELETE", xbox = "Y"},
  [298] = {name = "INPUT_REPLAY_PAUSE", qwerty = "SPACEBAR", xbox = "A"},
  [299] = {name = "INPUT_REPLAY_REWIND", qwerty = "ARROW DOWN", xbox = "LB"},
  [300] = {name = "INPUT_REPLAY_FFWD", qwerty = "ARROW UP", xbox = "RB"},
  [301] = {name = "INPUT_REPLAY_NEWMARKER", qwerty = "M", xbox = "A"},
  [302] = {name = "INPUT_REPLAY_RECORD", qwerty = "S", xbox = "(NONE)"},
  [303] = {name = "INPUT_REPLAY_SCREENSHOT", qwerty = "U", xbox = "DPAD UP"},
  [304] = {name = "INPUT_REPLAY_HIDEHUD", qwerty = "H", xbox = "R3"},
  [305] = {name = "INPUT_REPLAY_STARTPOINT", qwerty = "B", xbox = "(NONE)"},
  [306] = {name = "INPUT_REPLAY_ENDPOINT", qwerty = "N", xbox = "(NONE)"},
  [307] = {name = "INPUT_REPLAY_ADVANCE", qwerty = "ARROW RIGHT", xbox = "DPAD RIGHT"},
  [308] = {name = "INPUT_REPLAY_BACK", qwerty = "ARROW LEFT", xbox = "DPAD LEFT"},
  [309] = {name = "INPUT_REPLAY_TOOLS", qwerty = "T", xbox = "DPAD DOWN"},
  [310] = {name = "INPUT_REPLAY_RESTART", qwerty = "R", xbox = "BACK"},
  [311] = {name = "INPUT_REPLAY_SHOWHOTKEY", qwerty = "K", xbox = "DPAD DOWN"},
  [312] = {name = "INPUT_REPLAY_CYCLEMARKERLEFT", qwerty = "[", xbox = "DPAD LEFT"},
  [313] = {name = "INPUT_REPLAY_CYCLEMARKERRIGHT", qwerty = "]", xbox = "DPAD RIGHT"},
  [314] = {name = "INPUT_REPLAY_FOVINCREASE", qwerty = "NUMPAD +", xbox = "RB"},
  [315] = {name = "INPUT_REPLAY_FOVDECREASE", qwerty = "NUMPAD -", xbox = "LB"},
  [316] = {name = "INPUT_REPLAY_CAMERAUP", qwerty = "PAGE UP", xbox = "(NONE)"},
  [317] = {name = "INPUT_REPLAY_CAMERADOWN", qwerty = "PAGE DOWN", xbox = "(NONE)"},
  [318] = {name = "INPUT_REPLAY_SAVE", qwerty = "F5", xbox = "START"},
  [319] = {name = "INPUT_REPLAY_TOGGLETIME", qwerty = "C", xbox = "(NONE)"},
  [320] = {name = "INPUT_REPLAY_TOGGLETIPS", qwerty = "V", xbox = "(NONE)"},
  [321] = {name = "INPUT_REPLAY_PREVIEW", qwerty = "SPACEBAR", xbox = "(NONE)"},
  [322] = {name = "INPUT_REPLAY_TOGGLE_TIMELINE", qwerty = "ESC", xbox = "(NONE)"},
  [323] = {name = "INPUT_REPLAY_TIMELINE_PICKUP_CLIP", qwerty = "X", xbox = "(NONE)"},
  [324] = {name = "INPUT_REPLAY_TIMELINE_DUPLICATE_CLIP", qwerty = "C", xbox = "(NONE)"},
  [325] = {name = "INPUT_REPLAY_TIMELINE_PLACE_CLIP", qwerty = "V", xbox = "(NONE)"},
  [326] = {name = "INPUT_REPLAY_CTRL", qwerty = "LEFT CTRL", xbox = "(NONE)"},
  [327] = {name = "INPUT_REPLAY_TIMELINE_SAVE", qwerty = "F5", xbox = "(NONE)"},
  [328] = {name = "INPUT_REPLAY_PREVIEW_AUDIO", qwerty = "SPACEBAR", xbox = "RT"},
  [329] = {name = "INPUT_VEH_DRIVE_LOOK", qwerty = "LEFT MOUSE BUTTON", xbox = "(NONE)"},
  [330] = {name = "INPUT_VEH_DRIVE_LOOK2", qwerty = "RIGHT MOUSE BUTTON", xbox = "(NONE)"},
  [331] = {name = "INPUT_VEH_FLY_ATTACK2", qwerty = "RIGHT MOUSE BUTTON", xbox = "(NONE)"},
  [332] = {name = "INPUT_RADIO_WHEEL_UD", qwerty = "MOUSE DOWN", xbox = "RIGHT STICK"},
  [333] = {name = "INPUT_RADIO_WHEEL_LR", qwerty = "MOUSE RIGHT", xbox = "RIGHT STICK"},
  [334] = {name = "INPUT_VEH_SLOWMO_UD", qwerty = "SCROLLWHEEL DOWN", xbox = "LEFT STICK"},
  [335] = {name = "INPUT_VEH_SLOWMO_UP_ONLY", qwerty = "SCROLLWHEEL UP", xbox = "LEFT STICK"},
  [336] = {name = "INPUT_VEH_SLOWMO_DOWN_ONLY", qwerty = "SCROLLWHEEL DOWN", xbox = "LEFT STICK"},
  [337] = {name = "INPUT_VEH_HYDRAULICS_CONTROL_TOGGLE", qwerty = "X", xbox = "A"},
  [338] = {name = "INPUT_VEH_HYDRAULICS_CONTROL_LEFT", qwerty = "A", xbox = "LEFT STICK"},
  [339] = {name = "INPUT_VEH_HYDRAULICS_CONTROL_RIGHT", qwerty = "D", xbox = "LEFT STICK"},
  [340] = {name = "INPUT_VEH_HYDRAULICS_CONTROL_UP", qwerty = "LEFT SHIFT", xbox = "LEFT STICK"},
  [341] = {name = "INPUT_VEH_HYDRAULICS_CONTROL_DOWN", qwerty = "LEFT CTRL", xbox = "LEFT STICK"},
  [342] = {name = "INPUT_VEH_HYDRAULICS_CONTROL_UD", qwerty = "D", xbox = "LEFT STICK"},
  [343] = {name = "INPUT_VEH_HYDRAULICS_CONTROL_LR", qwerty = "LEFT CTRL", xbox = "LEFT STICK"},
  [344] = {name = "INPUT_SWITCH_VISOR", qwerty = "F11", xbox = "DPAD RIGHT"},
  [345] = {name = "INPUT_VEH_MELEE_HOLD", qwerty = "X", xbox = "A"},
  [346] = {name = "INPUT_VEH_MELEE_LEFT", qwerty = "LEFT MOUSE BUTTON", xbox = "LB"},
  [347] = {name = "INPUT_VEH_MELEE_RIGHT", qwerty = "RIGHT MOUSE BUTTON", xbox = "RB"},
  [348] = {name = "INPUT_MAP_POI", qwerty = "SCROLLWHEEL BUTTON (PRESS)", xbox = "Y"},
  [349] = {name = "INPUT_REPLAY_SNAPMATIC_PHOTO", qwerty = "TAB", xbox = "X"},
  [350] = {name = "INPUT_VEH_CAR_JUMP", qwerty = "E", xbox = "L3"},
  [351] = {name = "INPUT_VEH_ROCKET_BOOST", qwerty = "E", xbox = "L3"},
  [352] = {name = "INPUT_VEH_FLY_BOOST", qwerty = "LEFT SHIFT", xbox = "L3"},
  [353] = {name = "INPUT_VEH_PARACHUTE", qwerty = "SPACEBAR", xbox = "A"},
  [354] = {name = "INPUT_VEH_BIKE_WINGS", qwerty = "X", xbox = "A"},
  [355] = {name = "INPUT_VEH_FLY_BOMB_BAY", qwerty = "E", xbox = "DPAD RIGHT"},
  [356] = {name = "INPUT_VEH_FLY_COUNTER", qwerty = "E", xbox = "DPAD RIGHT"},
  [357] = {name = "INPUT_VEH_TRANSFORM", qwerty = "X", xbox = "A"},
}

Controls.InputsLookup = {}
for k,v in pairs(Controls.Inputs) do
  Controls.Inputs[k].index              = k
  Controls.InputsLookup[v.name]         = k
  Controls.InputsLookup[v.name:lower()] = k
end

Controls.JustPressed = function(index,pad)
  return IsControlJustPressed((pad or 0),index)
end

Controls.Pressed = function(index,pad)
  return IsControlPressed((pad or 0),index)
end

Controls.JustReleased = function(index,pad)
  return IsControlJustReleased((pad or 0),index)
end

Controls.DisabledJustPressed = function(index,pad)
  return IsDisabledControlJustPressed((pad or 0),index)
end

Controls.DisabledPressed = function(index,pad)
  return IsDisabledControlPressed((pad or 0),index)
end

Controls.DisabledJustReleased = function(index,pad)
  return IsDisabledControlJustReleased((pad or 0),index)
end

Controls.GetControl = function(index_or_name)
  if type(index_or_name) == "number" then
    return Controls.Inputs[index_or_name]
  else
    return Controls.Inputs[Controls.InputsLookup[index_or_name]]
  end
end

Controls.GetControlValue = function(index_or_name,key)
  if type(index_or_name) == "number" then
    return Controls.Inputs[index_or_name][key]
  else
    return Controls.Inputs[Controls.InputsLookup[index_or_name]][key]
  end
end

Controls.GetGroup = function(index_or_name)
  if type(index_or_name) == "number" then
    return Controls.Groups[index_or_name]
  else
    return Controls.Groups[Controls.GroupsLookup[index_or_name]]
  end
end